In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import json

#Load Google Places API key
from config import gkey

# File to Load
cities = "cities.csv"

# Read city data file and store in Pandas Data frames
city_data = pd.read_csv(cities)
city_data.head()

,City,Country,Latitude,Longitude,Weather,Temperature,Humidity,Wind Speed,Cloud Cover %
0,Rikitea,PF,-23.12,-134.97,Clear,75.63,77,18.41,8
1,Hithadhoo,MV,-0.60,73.08,Rain,81.28,79,9.28,98
2,Henties Bay,NaN,-22.12,14.28,Clouds,61.00,93,3.31,13
3,Asău,RO,46.43,26.40,Clouds,42.75,52,5.82,83
4,Phayao,TH,19.25,100.25,Rain,93.22,29,5.95,22

In [2]:
# Extract the cities with ideal weather
ideal_temp = city_data[(city_data["Temperature"] >= 60) & (city_data["Temperature"] <= 80)]
no_wind = ideal_temp[ideal_temp["Wind Speed"] < 10]
clear_skys = no_wind[no_wind["Cloud Cover %"] < 10]
clear_skys

,City,Country,Latitude,Longitude,Weather,Temperature,Humidity,Wind Speed,Cloud Cover %
29,Port Alfred,ZA,-33.59,26.89,Clear,66.00,84,4.00,2
75,Saint George,US,37.10,-113.58,Clear,64.67,21,9.17,1
80,Cidreira,BR,-30.18,-50.21,Clear,66.81,71,6.53,0
114,Mar del Plata,AR,-38.00,-57.56,Mist,63.90,88,7.00,5
139,San Rafael,AR,-34.62,-68.33,Clear,62.17,42,3.76,9
144,Port Macquarie,AU,-31.43,152.92,Clear,74.62,35,4.70,0
157,Port Shepstone,ZA,-30.74,30.45,Clear,70.21,58,5.26,1
159,Champawat,IN,29.33,80.10,Clear,62.47,24,2.55,0
164,Macaúbas,BR,-13.02,-42.70,Clear,71.40,65,0.63,0
223,Nioro,GM,13.35,-15.75,Clear,77.02,30,9.51,0
226,Taoudenni,ML,22.68,-3.98,Clear,77.22,16,9.10,0
230,Santiago del Estero,AR,-27.80,-64.26,Clear,65.59,60,7.47,0
256,Mossamedes,AO,-15.20,12.15,Clear,72.46,74,7.31,4
293,De Aar,ZA,-30.65,24.01,Clear,61.88,37,7.45,0
306,Dabola,GN,10.75,-11.12,Clear,78.94,39,3.76,0
356,Nachingwea,TZ,-10.38,38.77,Clear,67.62,86,1.21,9
370,Chui,UY,-33.70,-53.46,Clear,62.62,77,6.98,0
377,Port Charlotte,US,26.98,-82.09,Clear,73.27,83,4.70,1
382,Puerto del Rosario,ES,28.50,-13.86,Clear,65.57,77,4.70,7
432,São Borja,BR,-28.66,-56.00,Clear,61.21,64,5.53,0
451,St. Pete Beach,US,27.73,-82.74,Clear,70.93,69,4.70,1
452,Bubaque,GW,11.28,-15.83,Clear,78.87,70,9.86,0
488,Presidencia Roque Sáenz Peña,AR,-26.79,-60.44,Clear,61.79,59,3.38,0
518,Pokhara,NP,28.23,83.98,Clear,72.66,15,1.48,0
525,Tessalit,ML,20.20,1.01,Clear,73.53,14,4.88,0
539,Freetown,SL,8.48,-13.23,Clear,79.07,82,2.39,0
541,São Miguel do Araguaia,BR,-13.28,-50.16,Clear,75.02,72,2.21,0

In [3]:
latitude = -13.28
longitude = -50.16

# geocoordinates
target_coordinates = "8.48", "-13.23"
target_search = "Hotel"
target_radius = 8000
target_type = "hotel"

print(target_coordinates)

('8.48', '-13.23')

In [4]:
# set up a parameters dictionary
params = {
    "location": target_coordinates,
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": gkey
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# run a request using our params dictionary
response = requests.get(base_url, params=params)

In [5]:
print(response.url)

https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=8.48&location=-13.23&keyword=Hotel&radius=8000&type=hotel&key=AIzaSyDee3T3zUD2j7TkKj40tXuslHnxHj1arCo

In [6]:
# convert response to json
places_data = response.json()

# Print the json (pretty printed)
print(json.dumps(places_data, indent=4, sort_keys=True))

{
    "html_attributions": [],
    "results": [],
    "status": "INVALID_REQUEST"
}

In [7]:
# Print the name and address of the first restaurant that appears
print(places_data["results"][0]["name"])
print(places_data["results"][0]["vicinity"])

IndexError: list index out of range